### ISSUE TITLE
Getting error on Android after installing thirdweb

### ISSUE THREAD

**Issue by ShehrozAttique** [thirdweb-dev/js#7468]
I have added thirdweb on my expo react native project but on web it is working fine but on Android and getting this error
ERROR  TypeError: Cannot read property 'includes' of undefined

![Image](https://github.com/user-attachments/assets/5dfa074a-6d6d-4e35-a148-00b06cbe30c8)

**Comment by joaquim-verges** [comment]
Can you update the SDK to the latest version? Should be fixed there

**Comment by ShehrozAttique** [comment]
> Can you update the SDK to the latest version? Should be fixed there

I have tried with latest and older versions but the error remains
